name: Anita Csabai
markdown: kramdown

collections:
  classes:
    output: true
    permalink: /:collection/:name
    
defaults:
  - scope:
      path: ""
      type: "classes"
    values:
      layout: "classes"
